name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        version: [nightly]
      fail-fast: false
    steps:
    - uses: actions/checkout@v2
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: ${{ matrix.version }}
        override: true
        components: rustfmt, llvm-tools-preview
    # Using this instead of plain cargo install for a great speedup.
    # Downsides: it's experumental and has some security implications. Well,
    # this is an open source project without any secret keys in the CI pipeline
    # so it should be fine.
    - uses: actions-rs/install@v0.1
      with:
        crate: grcov
        use-tool-cache: true
    - name: Clean
      run: cargo clean
    - name: Build
      run: cargo build --verbose
      env:
        RUSTFLAGS: -Zinstrument-coverage
    - name: Test
      run: cargo test
      env:
        # cargo test builds some things too so we need to add this flag here as well
        RUSTFLAGS: -Zinstrument-coverage
    - name: Enforce formatting
      run: cargo fmt -- --check
    - name: Generate code coverage
      run: grcov . --binary-path ./target/debug/ -s . -t lcov --branch --ignore-not-existing --ignore "/*" -o lcov.info
    - uses: codecov/codecov-action@v1
      with:
        verbose: true
