name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        version: [nightly]
      fail-fast: false
    steps:
    - uses: actions/checkout@v2
    - uses: actions/cache@v2
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
    key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: ${{ matrix.version }}
        override: true
        components: rustfmt, llvm-tools-preview
    - name: Install grcov
      run: cargo install grcov
    - name: Clean
      run: cargo clean
    - name: Build
      run: cargo build --verbose
      env:
        RUSTFLAGS: -Zinstrument-coverage
    - name: Test
      run: cargo test
      env:
        LLVM_PROFILE_FILE: cachedir-%p-%m.profraw
    - name: Enforce formatting
      run: cargo fmt -- --check
    - name: Report code coverage
      run: |
        grcov . --binary-path ./target/debug/ -s . -t lcov --branch --ignore-not-existing --ignore "/*" -o lcov.info
        bash <(curl -s https://codecov.io/bash) -f lcov.info
