name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        version: [nightly]
      fail-fast: false
    steps:
    - uses: actions/checkout@v2
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: ${{ matrix.version }}
        override: true
        components: rustfmt, llvm-tools-preview
    # We need this cache, otherwise crgo install grcov takes ages (read: minutes)
    # which makes the CI take orders of magnituted longer than without it. Caching helps.
    # There are currently no nicer solutions to this, but using the cache action
    # to cache ~/.cargo/bin/ should be good enough.
    - name: Cache things installed with cargo
      uses: actions/cache@v1
      with:
        path: ~/.cargo/bin/
        key: ${{ runner.os }}-cargo-bin
    - name: Install grcov
      run: cargo install grcov
    - name: Clean
      run: cargo clean
    - name: Build
      run: cargo build --verbose
      env:
        RUSTFLAGS: -Zinstrument-coverage
    - name: Test
      run: cargo test
      env:
        # cargo test builds some things too so we need to add this flag here as well
        RUSTFLAGS: -Zinstrument-coverage
    - name: Enforce formatting
      run: cargo fmt -- --check
    - name: Generate code coverage
      run: grcov . --binary-path ./target/debug/ -s . -t lcov --branch --ignore-not-existing --ignore "/*" -o lcov.info
    - uses: codecov/codecov-action@v1
      with:
        verbose: true
